### PR TITLE
NALMS pvs for MR2K2, MR3K2, and MR4K2

### PR DESCRIPTION
**Pull request by nrwslac**
added NALMS pvs for MR2K2, MR3K2, and MR4K2.

### CODE REVIEW

**Comment by tangkong** [comment]
Did anything change in the first few lines of the file?  The diff says something changed but I can't pick out what...  

Otherwise the checks pass so it seems ok to merge

**Comment by nrwslac** [comment]
I cant tell. Editing a CSV file as the source across different OS and applications seems like a bad idea. @tangkong

**Comment by nrwslac** [comment]
I guess its easy enough to roll back if something breaks, ill merge it.

**Comment by tangkong** [comment]
I agree, but if the xml generates then things should be ok

**Pull request merged**
