### PR TITLE
ENH: add placeholder configs for each hutch

### PR DESCRIPTION
**Pull request by tangkong**
I've added placeholder configs for each of our hutches, to kickstart the process of getting NALMS set up across LCLS.

I've included the converted XMLs here for review, despite the fact that they will be regenerated by GHA.

### CODE REVIEW

**Comment by tangkong** [comment]
@tsgit , I somehow can't add you as a reviewer, but I'd appreciate your review on this to check that the XML files are compliant with the nalms backend.  

I've also added a second subdirectory here, which will require the git-sync settings to be updated.  Would you mind making those changes?  

Thanks!

**Comment by tsgit** [comment]
this looks reasonable, I have to confirm that phoebus alarm server works (starts up ok) with the skeletal xml.

question: are the names guaranteed to be unique, or could there be

KFE/<some config>
LFE/<some config>
<anotherdir>/<some config>

in the future.

right now I see configs for "instruments(?)" 

KFE: CRIX QRIX TMO TXI
LFE: CXI MEC MFX XCS XPP

in addition to KFE: GMDXGMD RTDSK0Vac SXR-EBD SXR-FEE

For gitsync sub-directory walk, should I expect additional sub-directories? if the sub-directory name is parametrized (to avoid name collision between filenames in KFE/ LFE/ whatever/) as an ENV variable, what is a meaningful name (as an env variable) for it.

**Comment by tsgit** [comment]
apologies for taking some time for the review, very busy week.

LGTM, ready to merge


As it is the xml file names match the <config name="..."> attribute, and the kustomize configmap generation from file uses the filename as key, which ideally matches the topic. This is all adhered to here. e.g. CXI-alarms.xml -> topic cxi-alarms for consistency.


The phoebus alarm server will load the skeletal xml config just fine and create the corresponding kafka topics 

logs from a pod startup
```
$ kcv logs phoebus-alrm-srv-cxi-0
Defaulted container "phoebus-alrm-srv-cxi" out of: phoebus-alrm-srv-cxi, initialize-pv-config (init), wait-on-kafka (init)
Created topic CXI-alarms.
Completed updating config for topic CXI-alarms.
Created topic CXI-alarmsCommand.
Completed updating config for topic CXI-alarmsCommand.
Created topic CXI-alarmsTalk.
Completed updating config for topic CXI-alarmsTalk.
2023-08-04 02:59:41 INFO [org.phoebus.applications.alarm] Loading settings from /tmp/alarm_server.properties
2023-08-04 02:59:41 INFO [java.util.prefs] Created user preferences directory.
2023-08-04 02:59:41 WARNING [org.phoebus.applications.alarm] Potentially conflicting setting: -settings/config_names:  and -config:CXI-alarms
2023-08-04 02:59:41 WARNING [org.phoebus.applications.alarm] Using argument -config instead of -settings
2023-08-04 02:59:41 WARNING [org.phoebus.applications.alarm] config_names: CXI-alarms
2023-08-04 02:59:41 INFO [org.phoebus.applications.alarm] Skipping import of/tmp/nalms/CXI.xml
2023-08-04 02:59:42 INFO [org.phoebus.applications.alarm] Setting xml file path to: /tmp/nalms/CXI.xml
2023-08-04 02:59:42 INFO [org.phoebus.applications.alarm] Loading settings from /tmp/alarm_server.properties
2023-08-04 02:59:42 WARNING [org.phoebus.applications.alarm] Potentially conflicting setting: -settings/config_names:  and -config:CXI-alarms
2023-08-04 02:59:42 WARNING [org.phoebus.applications.alarm] Using argument -config instead of -settings
2023-08-04 02:59:42 WARNING [org.phoebus.applications.alarm] config_names: CXI-alarms
2023-08-04 02:59:42 INFO [org.phoebus.applications.alarm] Alarm Server (PID 2172)
2023-08-04 02:59:42 INFO [org.phoebus.applications.alarm] Server: nalms-kafka-bootstrap:9092
2023-08-04 02:59:42 INFO [org.phoebus.applications.alarm] Config: CXI-alarms
2023-08-04 02:59:42 INFO [org.phoebus.applications.alarm] Extra Kafka Properties: 
2023-08-04 02:59:42 INFO [org.phoebus.applications.alarm] Importing model from: /tmp/nalms/CXI.xml
Reading new configuration from /tmp/nalms/CXI.xml
Fetching existing alarm configuration for "CXI-alarms" with 10 connection timeout, then waiting for it to remain stable for 4 seconds...
2023-08-04 02:59:45 INFO [org.phoebus.applications.alarm] Reading from start of CXI-alarms
Deleting existing CXI-alarms ...
Loading new CXI-alarms ...
Time to read XML                     : 00:00:00.011
Time to fetch existing configuration : 00:00:10
Time to delete existing configuration: 00:00:00.001
Time to load new configuration       : 00:00:00.089
Total                                : 00:00:10
Done.
2023-08-04 02:59:52 INFO [org.phoebus.applications.alarm] AlarmClientModel CXI-alarms shut down
2023-08-04 02:59:52 INFO [org.phoebus.applications.alarm] File checksum set to: be67b4d4f4d122fcdb2b9a6f8d397bca
2023-08-04 02:59:52 INFO [org.phoebus.applications.alarm] Fetching past alarm states...
2023-08-04 02:59:55 INFO [org.phoebus.applications.alarm] Reading from start of CXI-alarms
2023-08-04 03:00:02 INFO [org.phoebus.applications.alarm] Alarm state stabilized
2023-08-04 03:00:02 INFO [org.phoebus.applications.alarm] Start handling alarms
2023-08-04 03:00:02 INFO [org.phoebus.applications.alarm] Not using any heartbeat PV
2023-08-04 03:00:05 INFO [org.phoebus.applications.alarm] Reading updates for CXI-alarmsCommand
2023-08-04 03:00:05 INFO [org.phoebus.applications.alarm] Reading from start of CXI-alarms
```

and kafka topics
```
$ kubectl get kafkatopics | grep cxi-alarms
cxi-alarms---6e8aaadf1690b66c37d19a257c2c03fe569f403                                               nalms         1            3                    True
cxi-alarmscommand---dff1a4db53035b88ecf8421dfea0eb4a40e86609                                       nalms         1            3                    True
cxi-alarmstalk---25ca245b2a281e327aab73474ff7bc0f670c8e37                                          nalms         1            3                    True
```

I will create corresponding deployments in pcds-nalms k8s. Merging this can be done independently, though.

**Review by tsgit — APPROVED** [review]
LGTM

**Comment by tsgit** [comment]
I learned that KFE and LFE are basically labels for undulators in the "FE =
Front End" starting in the middle of the alphabet to allow addition on both
sides
hence a meaningful env var name might reference that, but I think
NALMS_CONFIG_DIR
or ALARMS_CONFIG_DIR is more flexible.

**Pull request merged**
